In [23]:
# Import the required libraries
import pandas as pd
import openpyxl
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3

print("Pandas:", pd.__version__)
print("Excel support: OK")

Pandas: 2.2.2
Excel support: OK

In [ ]:
# Load dataset and display the first few rows to check the dataset
df = df = pd.read_excel("data/Excel raw data.xlsx")  
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [17]:
df.info()  # Display information about the dataset, including data types and non-null counts

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 1.6+ MB

In [18]:
df.describe()  # Display summary statistics for numerical columns in the dataset

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2016-04-30 00:07:12.259355648,2016-05-03 23:06:58.571142912,55190.379428,229.858001,3.789574,0.156203,28.656896
min,1.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,2015-05-23 00:00:00,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,2016-06-26 00:00:00,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000
std,2885.163629,NaN,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108

In [30]:
df.shape  # Display the shape of the dataset (number of rows and columns)

(9994, 21)

In [20]:
# Checking for missing values in the dataset
missing_values=df.isnull().sum()
missing_values

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [ ]:
# checking for duplicates
duplicate_count=df.duplicated().sum()
duplicate_count

0

In [ ]:
# Display the data types of each column in the dataset
df.dtypes

Row ID                    int64
Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code               int64
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

The dataset contains no missing values or duplicated values and is therefore clean for further analysis.

In [26]:
# Create an in-memory SQLite database
conn = sqlite3.connect(":memory:")

# Convert the DataFrame into a SQL table
df.to_sql("sales", conn, index=False, if_exists="replace")

print("Excel data successfully converted to a SQLite table!")

Excel data successfully converted to a SQLite table!

In [38]:
# query to find top 5 customers by total sales
top_customers_query = """
SELECT "Customer ID", "Customer Name", SUM("Sales") AS TotalSales
FROM sales
GROUP BY "Customer ID", "Customer Name"
ORDER BY TotalSales DESC
LIMIT 5;
"""
top_five_customers = pd.read_sql_query(top_customers_query, conn)
top_five_customers

  Customer ID  Customer Name  TotalSales
0    SM-20320    Sean Miller   25043.050
1    TC-20980   Tamara Chand   19052.218
2    RB-19360   Raymond Buch   15117.339
3    TA-21385   Tom Ashbrook   14595.620
4    AB-10105  Adrian Barton   14473.571

In [40]:
# Top 5 products by quantity sold

top_products_query="""
select "Product ID", 
"Product Name", 
sum(sales) as totalsales, 
sum(Quantity) as totalquantity
from sales
group by "Product ID", "Product Name"
order by totalquantity desc
limit 5;
"""
top_five_by_quantity= pd.read_sql_query(top_products_query, conn)
top_five_by_quantity

,Product ID,Product Name,totalsales,totalquantity
0,OFF-BI-10001524,GBC Premium Transparent Covers with Diagonal L...,780.456,67
1,FUR-CH-10002647,"Situations Contoured Folding Chairs, 4/Set",3641.274,64
2,FUR-TA-10001095,Chromcraft Round Conference Tables,8209.059,61
3,FUR-CH-10003774,"Global Wood Trimmed Manager's Task Chair, Khaki",4166.884,59
4,OFF-BI-10004728,Wilson Jones Turn Tabs Binder Tool for Ring Bi...,212.080,59